codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    patch:
      default:
        enabled: no
        if_not_found: success
    project:
      default:
        informational: true
